services:
  action-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/joshyorko/yo-dawg-action-server:latest
    ports:
      - "4001:8087"
    volumes:
      - ./devdata:/action-server/actions/devdata
      - action-server-data:/action-server/datadir
      - ./yo-dawg-images:/action-server/actions/yo-dawg-images:rw
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - llm_network   # <-- Added this line

  ollama:
    image: ollama/ollama
    deploy:
    volumes:
      - ollama_volume:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - llm_network
    environment:
      - USE_GPU=${USE_GPU:-false}

  ollama-init:
    image: ollama/ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull gemma3:1b"
    volumes:
      - ollama_volume:/root/.ollama
    networks:
      - llm_network
    depends_on:
      - ollama

volumes:
  ollama_volume:
  action-server-data:

networks:
  llm_network:
    driver: bridge
