spec-version: v2

# Required: A short name for the action package
name: YoDawgActions

# Required: A description of what's in the action package.
description: Advanced Sema4ai Action Server for generating and posting custom "Yo Dawg" meme comments (with images) on LinkedIn posts using Model Context Protocol (MCP). Features autonomous meme generation, AI-generated captions and images, browser automation, and official signature for every comment.

# Package version number, recommend using semver.org
version: 0.0.1

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.8.3
  pypi:
    - sema4ai-actions=1.3.15
    - python-dotenv=1.1.1
    - openai=1.97.1
    - robocorp-browser=2.3.5
    - pydantic=2.11.7
    - Pillow=11.3.0

post-install:
   - playwright install --with-deps chromium


packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
    - ./**/__MACOSX
    - ./**/__pycache__
    - ./**/.git
    - ./node_modules/**
